version: "3"
services:
  db:
    image: mysql:5.7
    container_name: ccs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d

  server:
    build: ./server
    image: ccs/server
    container_name: ccs-server
    depends_on:
      - db
    ports:
      - "12345:12345"

  app:
    build: ./app/ccs
    image: ccs/app
    container_name: ccs-app
    depends_on:
      - server
    ports:
      - "4200:4200"
    # volumes:
    #   - ./app/ccs/dist/ccs:/usr/share/nginx/html
    #   - ./app/ccs/nginx.conf:/etc/nginx/conf.d/default.conf
