version: "3"
services:
  app:
    build: ./app/ccs
    image: ccs/app
    container_name: ccs-app
    depends_on:
      - server
    ports:
      - "4200:4200"

  server:
    build: ./server
    image: ccs/server
    container_name: ccs-server
    dns:
      - 119.29.29.29
      - 180.76.76.76
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "12345:12345"

  db:
    image: mysql:5.7
    container_name: ccs-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p123456"]
      timeout: 20s
      retries: 10
